# version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: my_database
    restart: always
    environment:
      POSTGRES_USER: smart_healthcare
      POSTGRES_PASSWORD: angelSuperSecret
      POSTGRES_DB: smart_healthcare_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: my_backend
    restart: always
    depends_on:
      - db
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql://smart_healthcare:angelSuperSecret@db:5432/smart_healthcare_db
    volumes:
      - ./backend:/app
      - /app/node_modules

  pgadmin:  # Move this under "services"
    image: dpage/pgadmin4
    container_name: my_pgadmin
    restart: always
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin-data:
