version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: my_database
    restart: always
    environment:
      POSTGRES_USER: smart_healthcare
      POSTGRES_PASSWORD: angelSuperSecret
      POSTGRES_DB: smart_healthcare_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: my_backend
    restart: always
    depends_on:
      - db
    command: node index.js
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://smart_healthcare:angelSuperSecret@db:5432/smart_healthcare_db
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: my_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    command: npm run dev

  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin
    restart: always
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin-data:
  frontend_node_modules:
